// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWD302_Project_HostelManagement.Data;

#nullable disable

namespace SWD302_Project_HostelManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318111456_InitFresh")]
    partial class InitFresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("AdminId")
                        .HasName("PK_Admin");

                    b.HasIndex(new[] { "Email" }, "UX_Admin_Email")
                        .IsUnique();

                    b.ToTable("Admin", null, t =>
                        {
                            t.HasCheckConstraint("CK_Admin_Status", "[status] IN ('Active', 'Inactive', 'Banned')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.BookingRequest", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reject_reason");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request_type")
                        .HasDefaultValueSql("'Booking'");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("BookingId")
                        .HasName("PK_BookingRequest");

                    b.HasIndex(new[] { "RoomId" }, "IX_BookingRequest_RoomId");

                    b.HasIndex(new[] { "Status" }, "IX_BookingRequest_Status");

                    b.HasIndex(new[] { "TenantId" }, "IX_BookingRequest_TenantId");

                    b.ToTable("BookingRequest", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingRequest_Status", "[status] IN ('Pending', 'Approved', 'Rejected', 'Cancelled', 'PendingPayment', 'DepositPaid', 'Confirmed')");

                            t.HasCheckConstraint("CK_BookingRequest_Type", "[request_type] IN ('Booking', 'Viewing')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HostelId")
                        .HasColumnType("int")
                        .HasColumnName("hostel_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("FavoriteId")
                        .HasName("PK_Favorite");

                    b.HasIndex("HostelId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Favorite_TenantId");

                    b.HasIndex(new[] { "TenantId", "HostelId" }, "UX_Favorite_TenantId_HostelId")
                        .IsUnique();

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Hostel", b =>
                {
                    b.Property<int>("HostelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hostel_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostelId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reject_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PendingApproval'");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("HostelId")
                        .HasName("PK_Hostel");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Hostel_OwnerId");

                    b.HasIndex(new[] { "Status" }, "IX_Hostel_Status");

                    b.ToTable("Hostel", null, t =>
                        {
                            t.HasCheckConstraint("CK_Hostel_Status", "[status] IN ('PendingApproval', 'Approved', 'Rejected', 'Deleted')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.HostelOwner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BusinessLicense")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("business_license");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("OwnerId")
                        .HasName("PK_HostelOwner");

                    b.HasIndex(new[] { "Email" }, "UX_HostelOwner_Email")
                        .IsUnique();

                    b.ToTable("HostelOwner", null, t =>
                        {
                            t.HasCheckConstraint("CK_HostelOwner_Status", "[status] IN ('Active', 'Inactive', 'Banned')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_content");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("recipient_email");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("PK_Notification");

                    b.HasIndex(new[] { "BookingId" }, "IX_Notification_BookingId");

                    b.HasIndex(new[] { "Status" }, "IX_Notification_Status");

                    b.ToTable("Notification", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notification_Status", "[status] IN ('Pending', 'Sent', 'Failed')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GatewayRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("gateway_ref");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("TransactionId")
                        .HasName("PK_PaymentTransaction");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "BookingId" }, "IX_PaymentTransaction_BookingId");

                    b.ToTable("PaymentTransaction", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransaction_Status", "[status] IN ('Pending', 'Success', 'Failed', 'Cancelled', 'VerificationFailed')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HostelId")
                        .HasColumnType("int")
                        .HasColumnName("hostel_id");

                    b.Property<string>("OwnerReply")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_reply");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ReviewId")
                        .HasName("PK_Review");

                    b.HasIndex("BookingId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "HostelId" }, "IX_Review_HostelId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<decimal?>("Area")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("area");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<int>("HostelId")
                        .HasColumnType("int")
                        .HasColumnName("hostel_id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price_per_month");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("room_number");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Available'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RoomId")
                        .HasName("PK_Room");

                    b.HasIndex(new[] { "HostelId" }, "IX_Room_HostelId");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Room_OwnerId");

                    b.HasIndex(new[] { "Status" }, "IX_Room_Status");

                    b.HasIndex(new[] { "HostelId", "RoomNumber" }, "UX_Room_HostelId_RoomNumber")
                        .IsUnique();

                    b.ToTable("Room", null, t =>
                        {
                            t.HasCheckConstraint("CK_Room_Status", "[status] IN ('Available', 'Reserved', 'Occupied', 'Maintenance', 'Inactive')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.RoomUpdateLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ChangedByOwnerId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_owner_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("StatusAfter")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status_after");

                    b.Property<string>("StatusBefore")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status_before");

                    b.HasKey("LogId")
                        .HasName("PK_RoomUpdateLog");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChangedByOwnerId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomUpdateLog", (string)null);
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identity_card");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("TenantId")
                        .HasName("PK_Tenant");

                    b.HasIndex(new[] { "Email" }, "UX_Tenant_Email")
                        .IsUnique();

                    b.ToTable("Tenant", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenant_Status", "[status] IN ('Active', 'Inactive', 'Banned')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.ViolationReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Evidence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidence");

                    b.Property<int?>("HostelId")
                        .HasColumnType("int")
                        .HasColumnName("hostel_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<int?>("ReportedTenantId")
                        .HasColumnType("int")
                        .HasColumnName("reported_tenant_id");

                    b.Property<int>("ReporterTenantId")
                        .HasColumnType("int")
                        .HasColumnName("reporter_tenant_id");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.HasKey("ReportId")
                        .HasName("PK_ViolationReport");

                    b.HasIndex("HostelId");

                    b.HasIndex("ReportedTenantId");

                    b.HasIndex("ReporterTenantId");

                    b.ToTable("ViolationReport", null, t =>
                        {
                            t.HasCheckConstraint("CK_ViolationReport_Status", "[status] IN ('Pending', 'Resolved', 'Dismissed')");
                        });
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.BookingRequest", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.Room", "Room")
                        .WithMany("BookingRequests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingRequest_Room");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Tenant", "Tenant")
                        .WithMany("BookingRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BookingRequest_Tenant");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Favorite", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.Hostel", "Hostel")
                        .WithMany("Favorites")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Hostel");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Tenant", "Tenant")
                        .WithMany("Favorites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Tenant");

                    b.Navigation("Hostel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Hostel", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.HostelOwner", "Owner")
                        .WithMany("Hostels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Hostel_HostelOwner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Notification", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.BookingRequest", "BookingRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Notification_BookingRequest");

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.PaymentTransaction", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.BookingRequest", "BookingRequest")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentTransaction_BookingRequest");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Tenant", "Tenant")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentTransaction_Tenant");

                    b.Navigation("BookingRequest");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Review", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.BookingRequest", "BookingRequest")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Review_BookingRequest");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Hostel", "Hostel")
                        .WithMany("Reviews")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Hostel");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Tenant", "Tenant")
                        .WithMany("Reviews")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Tenant");

                    b.Navigation("BookingRequest");

                    b.Navigation("Hostel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Room", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.Hostel", "Hostel")
                        .WithMany("Rooms")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Room_Hostel");

                    b.HasOne("SWD302_Project_HostelManagement.Models.HostelOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Room_HostelOwner");

                    b.Navigation("Hostel");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.RoomUpdateLog", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.BookingRequest", "BookingRequest")
                        .WithMany("RoomUpdateLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_RoomUpdateLog_BookingRequest");

                    b.HasOne("SWD302_Project_HostelManagement.Models.HostelOwner", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByOwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RoomUpdateLog_ChangedBy");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Room", "Room")
                        .WithMany("RoomUpdateLogs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RoomUpdateLog_Room");

                    b.Navigation("BookingRequest");

                    b.Navigation("ChangedBy");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.ViolationReport", b =>
                {
                    b.HasOne("SWD302_Project_HostelManagement.Models.Hostel", "Hostel")
                        .WithMany()
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ViolationReport_Hostel");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Tenant", "ReportedTenant")
                        .WithMany("ReportedViolations")
                        .HasForeignKey("ReportedTenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ViolationReport_ReportedTenant");

                    b.HasOne("SWD302_Project_HostelManagement.Models.Tenant", "Reporter")
                        .WithMany("ViolationReports")
                        .HasForeignKey("ReporterTenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ViolationReport_Reporter");

                    b.Navigation("Hostel");

                    b.Navigation("ReportedTenant");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.BookingRequest", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("RoomUpdateLogs");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Hostel", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.HostelOwner", b =>
                {
                    b.Navigation("Hostels");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Room", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("RoomUpdateLogs");
                });

            modelBuilder.Entity("SWD302_Project_HostelManagement.Models.Tenant", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("Favorites");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("ReportedViolations");

                    b.Navigation("Reviews");

                    b.Navigation("ViolationReports");
                });
#pragma warning restore 612, 618
        }
    }
}
